### ISSUE TITLE
`FutureResult` monad

### ISSUE THREAD

**Issue by katunilya** [katunilya/moona#41]
⛔ #43 

**Feature description**

When working with `Result` monad and async functions we might bump into variety of wrappers around functions to make it work. For that we need some dedicated `FutureResult` monad that internally combines everything. Compatible with `Result` and `Future`.

**Tasks**

- [ ] `>` sync Success handler
- [ ] `>>` async Success handler
- [ ] `<` sync Failure handler
- [ ] `<<` async Failure handler
- [ ] rewrite `Result`'s `>>` to `>`
- [ ] rewrite `Result`'s `<<` to `<`
- [ ] `Result`'s `>>` now produces `FutureResult` (Success)
- [ ] `Result`'s `<<` now produces `FutureResult` (Failure)
