### ISSUE TITLE
Add `Pipe` operator

### ISSUE THREAD

**Issue by katunilya** [katunilya/moona#42]
**Feature description**

Functional languages provide so called `pipe` operator. In F# for example it is `|>`. Pipe operator does very simple thing it moves argument on the left to be on the right from the right argument of `pipe`:

```fsharp
let (|>) x y = y x
```

This allows writing code in pipelines like:

```
obj 
|> do_smth_1 
|> do_smth_2 
|> do_smth_3
```

Override of `>>` and `<<` operators had been initially inspired by this. Currently it is implemented only for `Future` monad, but why not to provide functionality for sync values too?

**Tasks**

- [x] `Pipe` container that wraps some sync value inside
- [x] `>>` operator for executing async functions (`Pipe` converted to `Future`)
- [x] `>` operator for executing sync functions (`Pipe` remains `Pipe`)
- [x] `unpack` static method for unwrapping value from `Pipe`
- [x] Aliases for `>` and `>>` - `then` and `then_future`

---

Target syntax example:

```python
result: Future = (
   Pipe(path) 
   > read_file 
   > to_url 
   >> fetch_user
)
```

---

- [x] pipe then f: x->y --> pipe 
- [x] pipe then_future async f: x->y --> future 
- [x] pipe then_result f: x->result y --> result
- [x] pipe then_maybe f: x->maybe y --> maybe
- [x] pipe then_result_future async f: x->result y --> future_result
- [x] pipe then_maybe_future async f: x->maybe y --> future_maybe
- [x] future then f: x->y --> future 
- [x] future then_future async f: x->y --> future
- [x] future then_result f: x->result y --> future_result
- [x] future then_maybe f: x->maybe y --> future_maybe
- [x] future then_result_future async f: x->result y --> future_result
- [x] future then_maybe_future async f: x->maybe y --> future_maybe
- [x] result then f: ok->result y --> result
- [x] result then_future async f: ok->result y --> future_result
- [x] result otherwise f: bad->result y --> result
- [x] result otherwise_future async f: bad->result y --> future_result
- [x] maybe then f: some->maybe y --> maybe
- [x] maybe then_future async f: some->maybe y --> future_maybe
- [x] maybe otherwise f: nothing->maybe y --> maybe
- [x] maybe otherwise_future async f: nothing->maybe y --> future_maybe
- [x] future_result then f: ok->result y --> future_result
- [x] future_result then_future async f: ok->result y --> future_result
- [x] future_result otherwise f: bad->result y --> future_result
- [x] future_result otherwise_future async f: bad->result y --> future_result
- [x] future_maybe then f: some->maybe y --> future_maybe
- [x] future_maybe then_future async f: some->maybe y --> future_maybe
- [x] future_maybe otherwise f: nothing->maybe y --> future_maybe
- [x] future_maybe otherwise_future async f: nothing->maybe y --> future_maybe
