### ISSUE TITLE
Add `FutureMaybe` monad

### ISSUE THREAD

**Issue by katunilya** [katunilya/moona#44]
⛔ #43

**Feature description**

`Maybe` monad requires also working with async functions. For that we need to provide separated, but compatible `FutureMaybe` monad.

**Tasks**

- [ ] `>>` operator for async `Some` binding
- [ ] `>` operator for sync `Some` binding
- [ ] `<<` operator for async `Nothing` binding
- [ ] `<` operator for sync `Nothing` binding
- [ ] `>>` operator of `Maybe` returns `FutureMaybe`
- [ ] `<<` operator of `Maybe` returns `FutureMaybe`
- [ ] `>` operator of `Maybe` for sync `Some` binding
- [ ] `<` operator of `Maybe` for sync `Nothing` binding
